# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 896745d36a0cb8f1117cef75eb43e239ec6fc6e03d310bc2e1beb3b0a01f160420419a79838857ffafea5b92003ed4f61ed1c2de2676a2bca2fd2eb004e0b653

test:
  secret_key_base: e172e0731dcab502bd45d929e6d6714fd14eaa7eb184f76eef0e5225bebb147e93703e98e46d5d27f7d129b5216669e6ea83db72c2eb1ed7edf19a99bf98a10a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
